export const DEFAULT_LETTERS = [
	{ key: "q" },
	{ key: "w" },
	{ key: "e" },
	{ key: "r" },
	{ key: "t" },
	{ key: "y" },
	{ key: "u" },
	{ key: "i" },
	{ key: "o" },
	{ key: "p" },

	{ key: "space_1", icon: "" },
	{ key: "a" },
	{ key: "s" },
	{ key: "d" },
	{ key: "f" },
	{ key: "g" },
	{ key: "h" },
	{ key: "j" },
	{ key: "k" },
	{ key: "l" },
	{ key: "space_2", icon: "" },

	{ key: "enter", icon: "enter", class: "large" },
	{ key: "z" },
	{ key: "x" },
	{ key: "c" },
	{ key: "v" },
	{ key: "b" },
	{ key: "n" },
	{ key: "m" },
	{ key: "backspace", icon: "←", class: "large" },
];

export const DEFAULT_ROW_1 = [
	{ key: "q" },
	{ key: "w" },
	{ key: "e" },
	{ key: "r" },
	{ key: "t" },
	{ key: "y" },
	{ key: "u" },
	{ key: "i" },
	{ key: "o" },
	{ key: "p" },
];
export const DEFAULT_ROW_2 = [
	{ key: "a" },
	{ key: "s" },
	{ key: "d" },
	{ key: "f" },
	{ key: "g" },
	{ key: "h" },
	{ key: "j" },
	{ key: "k" },
	{ key: "l" },
];

export const DEFAULT_ROW_3 = [
	{ key: "enter", icon: "enter" },
	{ key: "z" },
	{ key: "x" },
	{ key: "c" },
	{ key: "v" },
	{ key: "b" },
	{ key: "n" },
	{ key: "m" },
	{ key: "backspace", icon: "←" },
];
